### PR TITLE
added note and diagram about the player number in track load packets

### PR DESCRIPTION
**Pull request by Swiftb0y**
I wasn't able to test if this renders properly and I'm also not good at explaining things...

### CODE REVIEW

**Comment by brunchboy** [comment]
If you click the Details link on the “Deploy preview ready!” message from Netlify above, you can see a rendered preview of the documentation site. You are correct that for now it is challenging to set up a local pipeline, because I am reliant on an unreleased Antora branch as well as an unreleased Antora plugin, which I use by building them from source checked out from GitLab. If you ever want help setting that up, though, I can certainly walk you through it, and you can look at the `build.sh` script in the `doc` folder.

**Comment by brunchboy** [comment]
Ah, but unfortunately the preview doesn’t work because it renders only the master branch, and you have quite correctly used a different branch for your pull request. Pity, I will have to see if there is anything I can do about that.

Anyway, what you are reporting is very strange! I have never seen a zero-based device number like that before. How did you verify this? Do you have multiple players with different numbers to test with? And it seems not to matter as far as having the load request actually work.

**Comment by brunchboy** [comment]
And I bet that “dest” is too long a subscript to fit in a single byte cell. I’ll take a look at that as well when I have time to try reproducing this with my players. Thanks for the contribution!

**Comment by brunchboy** [comment]
One last thought: To give you at least a bit of agency in testing your diagram renderings, you can render them individually by checking out and building the [`bytefield-svg` project](https://github.com/Deep-Symmetry/bytefield-svg) on its own, following the README.

Then you can edit the [`test.js` file](https://github.com/Deep-Symmetry/bytefield-svg/blob/master/test.js) to replace the `diagram` source with your own diagram. You will also need to explicitly insert the content of the [include file `example$status_shared.edn`](https://github.com/Deep-Symmetry/dysentery/blob/4c53571651bcf7fbaf03e48a8b47678c36b103b6/doc/modules/ROOT/examples/startup_shared.edn) that Antora includes at the beginning of the bytefield diagram block, since Antora isn’t there to do that for you.

> Sadly, because I put back-ticks in the include file, around the word `kind` in the doc string of `draw-packet-header`, you need to edit those out or the file is invalid Javascript. Getting rid of them won’t break anything, they are just to format the string nicely in markdown-aware documentation browsers.

But once you have done that, you can run `node test.js >test.svg` to generate the diagram. The end result looks like this (your text does barely fit, although _D<sub>d</sub>_ might look a bit nicer):

Screen Shot 2020-03-22 at 18 46 22

And here is the edited version of `test.js` in case my description was not clear enough:

```javascript
#!/usr/bin/env node

var generate = require('./lib.js');

var diagram = `
;; This is the include file, status_shared.edn
;; Some nice default background colors, used to distinguish header sections.
(defattrs :bg-green {:fill "#a0ffa0"})

(defn draw-packet-header
  "Generates the byte labels and first two rows of a standard DJ Link
  status, beat, or control packet with the specified kind byte."
  [kind]
  (draw-column-headers)
  (draw-related-boxes [0x51 0x73 0x70 0x74 0x31 0x57 0x6d 0x4a 0x4f 0x4c (hex-text kind 2 :bold)]
                      :bg-green)
  (draw-box nil [{:span 5} :box-above])
  (draw-box (text "Device Name (padded with " :plain [:hex "00"] ")") [{:span 15} :box-below])
  (draw-box 1))

;; This is your diagram source:
(draw-packet-header 0x19)
(draw-boxes [(hex-text 0 2 :bold) (text "D" :math)])
(draw-box (text "len" :math [:sub "r"]) {:span 2})
(draw-box (text "D" :math))
(draw-related-boxes (repeat 3 0))
(draw-box (text "D" :math [:sub "r"]))
(draw-box (text "S" :math [:sub "r"]))
(draw-box (text "T" :math [:sub "r"]))
(draw-box 0)
(draw-box (text "rekordbox" :math) {:span 4})
(draw-related-boxes (concat [0 0 0 0x32] (repeat 0x0b 0)))
(draw-box (text "D" :math [:sub "dest"]))
(draw-related-boxes (repeat 0x16 0))
`;

process.stdout.write(generate(diagram));
```

**Comment by brunchboy** [comment]
Looking at the diagram, we seem to have lost two bytes at the end. And indeed, `0x0b` + 1 + `0x16` is `0x22`, not `0x24`. 😄 But that is why helping you get a preview pipeline working is worthwhile. Is _D<sub>dest</sub>_ in the right place? You didn’t specify the byte offset in the text section.

**Comment by Swiftb0y** [comment]
> I have never seen a zero-based device number like that before. How did you verify this?

I just looked at the track load packets and then changed the player number on the device and this part of the messages seemed to correlate with the player numbers. I can try to verify it again though if you think that this behavior is so strange.

> Looking at the diagram, we seem to have lost two bytes at the end. And indeed, 0x0b + 1 + 0x16 is 0x22, not 0x24. smile But that is why helping you get a preview pipeline working is worthwhile. Is Ddest in the right place? You didn’t specify the byte offset in the text section.

Oh yeah its at the wrong place. I'll try to set up that local dev branch and then push a fix.

**Comment by Swiftb0y** [comment]
> > I have never seen a zero-based device number like that before. How did you verify this?
>
>I just looked at the track load packets and then changed the player number on the device and this part of the messages seemed to correlate with the player numbers. I can try to verify it again though if you think that this behavior is so strange.

Made some further tests and makes sense. Here's my pcap:
[Cdj+Rekordbox Load tracks to different players.pcapng.gz](https://github.com/Deep-Symmetry/dysentery/files/4369157/Cdj%2BRekordbox.Load.tracks.to.different.players.pcapng.gz)
You can use the filter `ip.addr == 192.168.178.39 && ip.addr == 192.168.178.56 && data.len == 0x58` to only show the track load packets. I tried it five times and I set the player to 2,1,1,4,3 which lines up with the 01,00,00,03,02 in the captured packets.

**Comment by brunchboy** [comment]
Thanks so much for the additional research! I was not doubting you, I was just expressing genuine surprise at this discovery because I had not seen such numbers before, But I know that you are looking at these packets in depth right now and I am not, so I fully expect to be surprised again by more discoveries you make. There are probably other places in other packets where similar values are sent, and I just never noticed them because they were not required to make the things I wanted to build work. 😄

**Pull request merged**
