### PR TITLE
Add Touch Audio packet analysis

### PR DESCRIPTION
**Pull request by nudge**
Here it is:
- Add Touch Audio packet analysis

Feel free to re-jig as necessary!

### CODE REVIEW

**Comment by brunchboy** [comment]
This is awesome, thanks! I’m just coming off a grueling sixty-hour work week, and very much want to spend some time implementing Beat Link Trigger features I had designed last weekend, so I won’t have a chance to integrate this right away, but I will as soon as I get some time, and hugely appreciate your contribution.

Your other recent PR also gave me the idea that I should make links from the elements in the byte field diagrams to the paragraphs that describe them, which would make the diagrams so much easier to use, but as you might have seen in #37, there seem to be browser bugs in the way today.

**Comment by EvanPurkhiser** [comment]
This is awesome, great work @nudge. Does the audio link feature definitely not work with the original 900nxs? I know it supported rekordbox linked audio

**Comment by nudge** [comment]
No worries, really happy to be able to contribute to this initiative!

**Comment by nudge** [comment]
> This is awesome, great work @nudge. Does the audio link feature definitely not work with the original 900nxs? I know it supported rekordbox linked audio

Thanks Evan. I haven't got an original 900nxs to test on, but everything I've read seems to indicate that it is not supported. I think Pioneer could support it with a firmware update, but not holding my breath for them to do that.

In any case I've designed hardware & firmware that implements the protocol and should work with any mixer, check it out here:
https://www.youtube.com/watch?v=_w24FztYWY4
Might do a small run of them if you are interested in getting your hands on one :) Also @brunchboy let me know if you want one and I can send one out to you!

**Comment by EvanPurkhiser** [comment]
Wow!!! Absolutely incredible work. I would definitely love to get my hands on this if you do a small batch

**Comment by brunchboy** [comment]
I was blown away by that video when I was sent the link by one of my community members on Zulip. I don’t find myself using non-Pioneer mixers enough to justify having one myself, but I definitely plan to add a link to your project somewhere in the Beat Link Trigger user guide. Let me know if there’s a good landing page to which I should direct people, or if you just want me to link to that video, or hold off until you have something more appropriate ready.

**Comment by EvanPurkhiser** [comment]
I'v snooped all around @nudge's awesome portfolio and found this :) https://nudge.id.au/cardinia-mini/index.html

**Comment by nudge** [comment]
👍 Theres a massive shortage of the [microcontroller](https://octopart.com/lpc54606j512bd100e-nxp+semiconductors-81000240?r=sp) I use, so hopefully the supply chain gets back on its feet shortly :)

Feel free to link to that page for now, not really sure where I am going to go with the project to be honest!

**Comment by brunchboy** [comment]
Ok, I will use that page. I want people to know what you’ve done, anyway. 😄 (And even car factories are being forced to idle due to lack of chips, so this shortage is not surprising, although it’s disappointing. My partner had quite the struggle to score a top-end graphics card this winter.)

**Comment by nudge** [comment]
Coolio, will add a link back to the dysentery project on the page as well :)

I'm thinking to open source the prodj link library that powers it (written in C), though it is a bit tricky since it relies on FreeRTOS and lwIP. If i get some time i'll create an abstraction layer so it is easier to port. I will most likely open source the hardware as well, at least the schematics, gerbers and BOM.

Also, checked your work on Prolink Tools @EvanPurkhiser, super cool!!

**Comment by brunchboy** [comment]
Yes, license compatibility can be tricky! I had to add some abstraction layers and even socket isolators in my own libraries a few times for that reason. Ok, the link is up on the master branch of the Beat Link Trigger user guide, on the [Integration Examples](https://blt-guide.deepsymmetry.org/beat-link-trigger/integration) page.

But you’re right, I should link to it from the Dysentery project read me page as well. I just added a list of related projects, including Cardinia MIni, Evan’s, and python-prodj-link. If anyone can remember others that seem to be active, let me know.

And thanks for the back link to there!

**Comment by nudge** [comment]
Started open-sourcing the hardware schematics and BOM 🥁 -> https://github.com/nudge/cardinia-mini

**Pull request merged**
