### PR TITLE
Fix minor typo in readme

### PR DESCRIPTION
**Pull request by tmm1**

### CODE REVIEW

**Comment by brunchboy** [comment]
Thank you for catching this. While looking at it, I noticed that the link takes people to a page that is _still_ offering a Java 8 installer, which is insane in 2024! We should probably update the link target at the same time, I was thinking perhaps https://www.oracle.com/java/technologies/downloads/ unless you know of a more vendor-neutral modern starting point?

**Comment by tmm1** [comment]
Good point! I know about https://whichjdk.com/ but JDK is overkill here. Perhaps https://adoptium.net/temurin/releases/?package=jre

**Comment by brunchboy** [comment]
I think you’re right, the WhichJDK site would overwhelm people with details they are not caring about while getting started with this project (even though the concepts of JDK vs. JRE were eliminated with Project Jigsaw and modules/jlink). The Temurin one might be nice, although I am not sure everyone (especially some macOS users) will know what “aarch64” means. As much as I hate to admit it, the Oracle page is slightly more approachable/understandable. Let’s go with that.

**Comment by brunchboy** [comment]
Well, I have to pack and head off to Electric Forest, so in the interest of not delaying this improvement for a week, I will merge this PR now, and we can adjust the URL later.

**Comment by tmm1** [comment]
Enjoy! I'm just getting out of Bonnaroo and still recovering. I will throw up another PR next week once I get home.

**Pull request merged**
